/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-15T16:20:39.864527269Z[GMT]
 * <br>
*  The generated test suite contains 2 tests
 * <br>
*  Covered targets: 9
 * <br>
*  Used time: 0h 1m 8s
 * <br>
*  Needed budget for current results: 31%
 * <br>
*  This file contains test cases that are likely to indicate faults.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_ts-preserve-service_admin_faults {

    
    private static String baseUrlOfSut = "http://localhost:8888";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (500) POST:/api/v1/preserveservice/preserve
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_0_postOnPreserveShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/preserveservice/preserve'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NzYyNjk5NjksImV4cCI6MTc3NjI3MzU2OX0.Bi8PWcl0UyVvutl7AxfiQM7yqpsXkaMNhjYfYJV7RKg") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"accountId\" : \"2L\", " + 
                    " \"from\" : \"qSVVfHy\", " + 
                    " \"to\" : \"fYQ02S\", " + 
                    " \"foodName\" : \"cAA7yyh74bnkiLW\", " + 
                    " \"foodPrice\" : 1.4440303357928526E8, " + 
                    " \"storeName\" : \"DToLsn6MPxo0WX\", " + 
                    " \"handleDate\" : \"wP\", " + 
                    " \"consigneeWeight\" : -1.2330590756151125E8, " + 
                    " \"isWithin\" : false " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/preserveservice/preserve")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/preserveservice/preserve"))
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("931ba7bb-785"));
    }
    
    
    /**
    * Calls:
    * (403) POST:/api/v1/preserveservice/preserve
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_1_postOnPreserveReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/preserveservice/preserve'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NzYyNjk5NjksImV4cCI6MTc3NjI3MzU2OX0.Bi8PWcl0UyVvutl7AxfiQM7yqpsXkaMNhjYfYJV7RKg") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"tripId\" : \"3jimiLy03\", " + 
                    " \"seatType\" : 322, " + 
                    " \"date\" : \"2001-10-17\", " + 
                    " \"to\" : \"MI\", " + 
                    " \"assurance\" : 778, " + 
                    " \"foodName\" : \"\", " + 
                    " \"foodPrice\" : 8.175752536181594E8, " + 
                    " \"stationName\" : \"o_gVTuaHwXTC1x\", " + 
                    " \"handleDate\" : \"W\", " + 
                    " \"consigneeName\" : \"vZk0m5a_\", " + 
                    " \"consigneePhone\" : \"HJEOWEQWFq\" " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/preserveservice/preserve")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }


}
