/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-15T04:44:50.858476018Z[GMT]
 * <br>
*  The generated test suite contains 2 tests
 * <br>
*  Covered targets: 9
 * <br>
*  Used time: 0h 2m 10s
 * <br>
*  Needed budget for current results: 100%
 * <br>
*  This file contains test cases that are likely to indicate faults.
*/
public class EvoMaster_ts_admin_order_service_none_faults {

    
    private static String baseUrlOfSut = "http://localhost:8888";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (503) PUT:/api/v1/adminorderservice/adminorder
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_0_putOnAdminorderReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 503 not defined for path '/adminorderservice/adminorder'.
        given().accept("application/json")
                .contentType("application/json")
                .body(" { " + 
                    " \"id\": \"p2CDxYcDB2cd\", " + 
                    " \"boughtDate\": \"2046-11-19\", " + 
                    " \"travelDate\": \"2058-03-21\", " + 
                    " \"travelTime\": \"2080-02-24T20:42:53.846+10:08\", " + 
                    " \"accountId\": \"kdGbUa5f\", " + 
                    " \"contactsDocumentNumber\": \"FL_4SnYN7TZSD\", " + 
                    " \"from\": \"LBSYRYOX9fAu\", " + 
                    " \"status\": 148, " + 
                    " \"price\": 0.9115419626555878 " + 
                    " } ")
                .put(baseUrlOfSut + "/api/v1/adminorderservice/adminorder")
                .then()
                .statusCode(503)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminorderservice/adminorder"))
                .body("'status'", numberMatches(503.0))
                .body("'error'", containsString("Service Unavailable"))
                .body("'requestId'", containsString("0f6fe5e0-171"));
    }
    
    
    /**
    * Calls:
    * (503) DELETE:/api/v1/adminorderservice/adminorder/{orderId}/{trainNumber}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_1_deleteOnAdminordReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 503 not defined for path '/adminorderservice/adminorder/{orderId}/{trainNumber}'.
        given().accept("application/json")
                .delete(baseUrlOfSut + "/api/v1/adminorderservice/adminorder/SasrzOoK0DB7JmOw/dWY3")
                .then()
                .statusCode(503)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminorderservice/adminorder/SasrzOoK0DB7JmOw/dWY3"))
                .body("'status'", numberMatches(503.0))
                .body("'error'", containsString("Service Unavailable"))
                .body("'requestId'", containsString("0f6fe5e0-172"));
    }


}
