/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-15T17:51:40.728604681Z[GMT]
 * <br>
*  The generated test suite contains 4 tests
 * <br>
*  Covered targets: 19
 * <br>
*  Used time: 0h 1m 15s
 * <br>
*  Needed budget for current results: 62%
 * <br>
*  This file contains test cases that are likely to indicate faults.
*/
public class EvoMaster_ts_admin_basic_service_user_faults {

    
    private static String baseUrlOfSut = "http://localhost:8888";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (500) GET:/api/v1/adminbasicservice/adminbasic/prices
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_0_getOnPricesShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmZHNlX21pY3Jvc2VydmljZSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpZCI6IjRkMmE0NmM3LTcxY2ItNGNmMS1iNWJiLWI2ODQwNmQ5ZGE2ZiIsImlhdCI6MTc3ODQyNTUzOSwiZXhwIjoxNzc4NDI5MTM5fQ.rEhlW9XbCqYjLljFHLUeYlc4zfJjUAZiCmX8JODiMT0") // Fixed Headers
                .get(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminbasicservice/adminbasic/prices"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("74eda16a-772"));
    }
    
    
    /**
    * Calls:
    * (500) POST:/api/v1/adminbasicservice/adminbasic/prices
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_1_postOnPricesShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("application/json")
                .contentType("application/json")
                .body(" { " + 
                    " \"id\": \"U\", " + 
                    " \"trainType\": \"EvBRzJ\", " + 
                    " \"basicPriceRate\": 0.7341814194420727, " + 
                    " \"firstClassPriceRate\": 0.9419335572639792 " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminbasicservice/adminbasic/prices"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("74eda16a-773"));
    }
    
    
    /**
    * Calls:
    * (403) POST:/api/v1/adminbasicservice/adminbasic/prices
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_2_postOnPricesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmZHNlX21pY3Jvc2VydmljZSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpZCI6IjRkMmE0NmM3LTcxY2ItNGNmMS1iNWJiLWI2ODQwNmQ5ZGE2ZiIsImlhdCI6MTc3ODQyNTUzOSwiZXhwIjoxNzc4NDI5MTM5fQ.rEhlW9XbCqYjLljFHLUeYlc4zfJjUAZiCmX8JODiMT0") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"trainType\": \"UNbDGt5vHnP\", " + 
                    " \"routeId\": \"yty3XiJ1l\" " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (500) DELETE:/api/v1/adminbasicservice/adminbasic/stations/{id}
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_3_deleteOnStationShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/adminbasicservice/adminbasic/stations/{id}'.
        given().accept("application/json")
                .delete(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/stations/DqUQxCfznHgbHKcJ")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminbasicservice/adminbasic/stations/DqUQxCfznHgbHKcJ"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("74eda16a-769"));
    }


}
