/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2025-12-18T04:10:24.755675063Z[GMT]
 * <br>
*  The generated test suite contains 3 tests
 * <br>
*  Covered targets: 14
 * <br>
*  Used time: 0h 1m 5s
 * <br>
*  Needed budget for current results: 29%
 * <br>
*  This file contains test cases that are likely to indicate faults.
*/
public class EvoMaster_Test_faults {

    
    private static String baseUrlOfSut = "http://localhost:8888";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (500) PUT:/api/v1/adminorderservice/adminorder
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_0_putOnAdminorderShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/adminorderservice/adminorder'.
        given().accept("application/json")
                .contentType("application/json")
                .body(" { " + 
                    " \"boughtDate\": \"1981-04-16\", " + 
                    " \"travelTime\": \"1925-00-13T23:27:21.011Z\", " + 
                    " \"accountId\": \"JThVX\", " + 
                    " \"documentType\": 131, " + 
                    " \"contactsDocumentNumber\": \"_UV71q7MVS\", " + 
                    " \"trainNumber\": \"gwpTsBZ\", " + 
                    " \"from\": \"xQMnM1QJRfA583H\", " + 
                    " \"to\": \"\", " + 
                    " \"status\": 307, " + 
                    " \"price\": 0.09831715456761358 " + 
                    " } ")
                .put(baseUrlOfSut + "/api/v1/adminorderservice/adminorder")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminorderservice/adminorder"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("8a3d4396-1470"));
    }
    
    
    /**
    * Calls:
    * (500) DELETE:/api/v1/adminorderservice/adminorder/{orderId}/{trainNumber}
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_1_deleteOnAdminordShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/adminorderservice/adminorder/{orderId}/{trainNumber}'.
        given().accept("application/json")
                .delete(baseUrlOfSut + "/api/v1/adminorderservice/adminorder/J3I9tx/ZgHMmJQBEa")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminorderservice/adminorder/J3I9tx/ZgHMmJQBEa"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("8a3d4396-1473"));
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/api/v1/adminorderservice/adminorder/{orderId}/{trainNumber}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_2_deleteOnAdminordReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/adminorderservice/adminorder/{orderId}/{trainNumber}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmZHNlX21pY3Jvc2VydmljZSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpZCI6IjRkMmE0NmM3LTcxY2ItNGNmMS1iNWJiLWI2ODQwNmQ5ZGE2ZiIsImlhdCI6MTc2NjAzMDk1NiwiZXhwIjoxNzY2MDM0NTU2fQ.eLR4D_Ot6KHCDg3DM90CaFLdVw-sdB0yG0hcnlNGRkQ") // Fixed Headers
                .delete(baseUrlOfSut + "/api/v1/adminorderservice/adminorder/jfYr7b/ju2QkTwK5")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }


}
