/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-15T18:21:29.341029854Z[GMT]
 * <br>
*  The generated test suite contains 6 tests
 * <br>
*  Covered targets: 26
 * <br>
*  Used time: 0h 1m 39s
 * <br>
*  Needed budget for current results: 78%
 * <br>
*  This file contains test cases that are likely to indicate faults.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_ts_admin_basic_service_admin_faults {

    
    private static String baseUrlOfSut = "http://localhost:8888";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * 1 - (500) POST:/api/v1/adminbasicservice/adminbasic/prices
    * 2 - (403) POST:/api/v1/adminbasicservice/adminbasic/prices
    * 3 - (500) POST:/api/v1/adminbasicservice/adminbasic/prices
    * 4 - (500) POST:/api/v1/adminbasicservice/adminbasic/prices
    * 5 - (500) POST:/api/v1/adminbasicservice/adminbasic/prices
    * 6 - (403) POST:/api/v1/adminbasicservice/adminbasic/prices
    * 7 - (500) GET:/api/v1/adminbasicservice/adminbasic/prices
    * Found 12 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_0_getOnPricesShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiI0NjgwZDY4ZS0zNWMyLTQzOTgtOGQyMS00Mzk2MzNlNWViZWEiLCJpYXQiOjE3Nzg0NDQyODQsImV4cCI6MTc3ODQ0Nzg4NH0.gCgFBxwAM_LbzhIJRfPfrQgqAWiv1ZRqWKDJeavqQfg") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"id\" : \"QiqjqCI0xe\", " + 
                    " \"basicPriceRate\" : 1.0433332756700285E7 " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminbasicservice/adminbasic/prices"))
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("7323347c-108"));
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiI0NjgwZDY4ZS0zNWMyLTQzOTgtOGQyMS00Mzk2MzNlNWViZWEiLCJpYXQiOjE3Nzg0NDQyODQsImV4cCI6MTc3ODQ0Nzg4NH0.gCgFBxwAM_LbzhIJRfPfrQgqAWiv1ZRqWKDJeavqQfg") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"trainType\" : \"umQm6Rlf2iD\", " + 
                    " \"routeId\" : \"wOg\" " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiI0NjgwZDY4ZS0zNWMyLTQzOTgtOGQyMS00Mzk2MzNlNWViZWEiLCJpYXQiOjE3Nzg0NDQyODQsImV4cCI6MTc3ODQ0Nzg4NH0.gCgFBxwAM_LbzhIJRfPfrQgqAWiv1ZRqWKDJeavqQfg") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"id\" : \"BdwDuaQ\", " + 
                    " \"trainType\" : \"jtdjhEsGGh\", " + 
                    " \"routeId\" : \"EbqQpQM\" " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminbasicservice/adminbasic/prices"))
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("7323347c-111"));
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiI0NjgwZDY4ZS0zNWMyLTQzOTgtOGQyMS00Mzk2MzNlNWViZWEiLCJpYXQiOjE3Nzg0NDQyODQsImV4cCI6MTc3ODQ0Nzg4NH0.gCgFBxwAM_LbzhIJRfPfrQgqAWiv1ZRqWKDJeavqQfg") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"firstClassPriceRate\" : -7.714105333496478E8 " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminbasicservice/adminbasic/prices"))
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("7323347c-112"));
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiI0NjgwZDY4ZS0zNWMyLTQzOTgtOGQyMS00Mzk2MzNlNWViZWEiLCJpYXQiOjE3Nzg0NDQyODQsImV4cCI6MTc3ODQ0Nzg4NH0.gCgFBxwAM_LbzhIJRfPfrQgqAWiv1ZRqWKDJeavqQfg") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"id\" : \"hBmkCbw27z\", " + 
                    " \"basicPriceRate\" : -1.560206776070894E8 " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminbasicservice/adminbasic/prices"))
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("7323347c-113"));
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiI0NjgwZDY4ZS0zNWMyLTQzOTgtOGQyMS00Mzk2MzNlNWViZWEiLCJpYXQiOjE3Nzg0NDQyODQsImV4cCI6MTc3ODQ0Nzg4NH0.gCgFBxwAM_LbzhIJRfPfrQgqAWiv1ZRqWKDJeavqQfg") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"trainType\" : \"U0Ms4t7EZto\" " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiI0NjgwZDY4ZS0zNWMyLTQzOTgtOGQyMS00Mzk2MzNlNWViZWEiLCJpYXQiOjE3Nzg0NDQyODQsImV4cCI6MTc3ODQ0Nzg4NH0.gCgFBxwAM_LbzhIJRfPfrQgqAWiv1ZRqWKDJeavqQfg") // Fixed Headers
                .get(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminbasicservice/adminbasic/prices"))
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("7323347c-116"));
    }
    
    
    /**
    * Calls:
    * (500) POST:/api/v1/adminbasicservice/adminbasic/prices
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_1_postOnPricesShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiI0NjgwZDY4ZS0zNWMyLTQzOTgtOGQyMS00Mzk2MzNlNWViZWEiLCJpYXQiOjE3Nzg0NDQyODQsImV4cCI6MTc3ODQ0Nzg4NH0.gCgFBxwAM_LbzhIJRfPfrQgqAWiv1ZRqWKDJeavqQfg") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"routeId\" : \"UOvuW0dvLAfV3Mo\", " + 
                    " \"basicPriceRate\" : -1.3838933705636342E9, " + 
                    " \"firstClassPriceRate\" : -6.796338399002931E8 " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminbasicservice/adminbasic/prices"))
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("7323347c-95"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/v1/adminbasicservice/adminbasic/prices
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_2_getOnPricesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type [Path '/data'] Instance type (array) does not match any allowed primitive type (allowed: ["object"])
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiI0NjgwZDY4ZS0zNWMyLTQzOTgtOGQyMS00Mzk2MzNlNWViZWEiLCJpYXQiOjE3Nzg0NDQyODQsImV4cCI6MTc3ODQ0Nzg4NH0.gCgFBxwAM_LbzhIJRfPfrQgqAWiv1ZRqWKDJeavqQfg") // Fixed Headers
                .get(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(1))
                .body("'msg'", containsString("Success"))
                .body("'data'.size()", equalTo(982))
                .body("'data'[0].'trainType'", nullValue())
                .body("'data'[0].'routeId'", nullValue())
                .body("'data'[0].'basicPriceRate'", numberMatches(0.0))
                .body("'data'[0].'firstClassPriceRate'", numberMatches(0.0))
                .body("'data'[1].'trainType'", nullValue())
                .body("'data'[1].'routeId'", containsString("YXS4EvuRkYHnfxu"))
                .body("'data'[1].'basicPriceRate'", numberMatches(0.0))
                .body("'data'[1].'firstClassPriceRate'", numberMatches(0.0))
                .body("'data'[2].'trainType'", nullValue())
                .body("'data'[2].'routeId'", nullValue())
                .body("'data'[2].'basicPriceRate'", numberMatches(0.0))
                .body("'data'[2].'firstClassPriceRate'", numberMatches(0.0))
                ; // Skipping assertions on the remaining 979 elements. This limit of 3 elements can be increased in the configurations
    }
    
    
    /**
    * Calls:
    * (403) POST:/api/v1/adminbasicservice/adminbasic/prices
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_3_postOnPricesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiI0NjgwZDY4ZS0zNWMyLTQzOTgtOGQyMS00Mzk2MzNlNWViZWEiLCJpYXQiOjE3Nzg0NDQyODQsImV4cCI6MTc3ODQ0Nzg4NH0.gCgFBxwAM_LbzhIJRfPfrQgqAWiv1ZRqWKDJeavqQfg") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"id\" : \"BdwDuaQ\", " + 
                    " \"trainType\" : \"jtdjhEsGGh\", " + 
                    " \"routeId\" : \"EbqQpQM\" " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (500) DELETE:/api/v1/adminbasicservice/adminbasic/stations/{id}
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_4_deleteOnStationShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/adminbasicservice/adminbasic/stations/{id}'.
        given().accept("application/json")
                .delete(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/stations/wxiR0SPSOaW8")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminbasicservice/adminbasic/stations/wxiR0SPSOaW8"))
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("7323347c-91"));
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/api/v1/adminbasicservice/adminbasic/stations/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_5_deleteOnStationReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/adminbasicservice/adminbasic/stations/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiI0NjgwZDY4ZS0zNWMyLTQzOTgtOGQyMS00Mzk2MzNlNWViZWEiLCJpYXQiOjE3Nzg0NDQyODQsImV4cCI6MTc3ODQ0Nzg4NH0.gCgFBxwAM_LbzhIJRfPfrQgqAWiv1ZRqWKDJeavqQfg") // Fixed Headers
                .delete(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/stations/Im")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }


}
