/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2025-12-18T04:09:13.703953068Z[GMT]
 * <br>
*  The generated test suite contains 2 tests
 * <br>
*  Covered targets: 9
 * <br>
*  Used time: 0h 1m 3s
 * <br>
*  Needed budget for current results: 31%
 * <br>
*  This file contains test cases that are likely to indicate faults.
*/
public class EvoMaster_Test_faults {

    
    private static String baseUrlOfSut = "http://localhost:8888";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (500) POST:/api/v1/preserveservice/preserve
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_0_postOnPreserveShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/preserveservice/preserve'.
        given().accept("application/json")
                .contentType("application/json")
                .body(" { " + 
                    " \"accountId\": \"6eE7vKPMeivz\", " + 
                    " \"tripId\": \"QvHx1clR5omo\", " + 
                    " \"seatType\": 251, " + 
                    " \"date\": \"1924-11-21\", " + 
                    " \"from\": \"qKw_BfTZUlFAZ_6n\", " + 
                    " \"to\": \"Gg\", " + 
                    " \"assurance\": 992, " + 
                    " \"foodType\": 94, " + 
                    " \"storeName\": \"LJdBekSF\", " + 
                    " \"handleDate\": \"M055bId\", " + 
                    " \"consigneeWeight\": 0.35361882669535705 " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/preserveservice/preserve")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/preserveservice/preserve"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("7b391ef9-1399"));
    }
    
    
    /**
    * Calls:
    * (403) POST:/api/v1/preserveservice/preserve
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_1_postOnPreserveReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/preserveservice/preserve'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmZHNlX21pY3Jvc2VydmljZSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpZCI6IjRkMmE0NmM3LTcxY2ItNGNmMS1iNWJiLWI2ODQwNmQ5ZGE2ZiIsImlhdCI6MTc2NjAzMDg4NywiZXhwIjoxNzY2MDM0NDg3fQ.xdVt-PdwYRe5wwzaINFovFHXmVZVi1t2sIRlLHctgO0") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"accountId\": \"aOHgOBqx16\", " + 
                    " \"contactsId\": \"oOOChDFfm7e7gz4\", " + 
                    " \"tripId\": \"VedlMFYXjSjw0v\", " + 
                    " \"date\": \"2044-01-31\", " + 
                    " \"from\": \"BMLwsb976K5\", " + 
                    " \"to\": \"nu64tuMECky6Nq7w\", " + 
                    " \"assurance\": 756, " + 
                    " \"foodType\": 222, " + 
                    " \"foodName\": \"\", " + 
                    " \"storeName\": \"33TZsxxva\", " + 
                    " \"consigneeName\": \"Alont2RgQJ0\", " + 
                    " \"consigneePhone\": \"vA_gpfGXjLNEgLvZ\", " + 
                    " \"consigneeWeight\": 0.1603586509324817 " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/preserveservice/preserve")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }


}
