/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-15T18:30:43.405383062Z[GMT]
 * <br>
*  The generated test suite contains 2 tests
 * <br>
*  Covered targets: 9
 * <br>
*  Used time: 0h 1m 2s
 * <br>
*  Needed budget for current results: 17%
 * <br>
*  This file contains test cases that are likely to indicate faults.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_ts-preserve-service_admin_faults {

    
    private static String baseUrlOfSut = "http://localhost:8888";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (500) POST:/api/v1/preserveservice/preserve
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_0_postOnPreserveShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/preserveservice/preserve'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NzYyNzc3NzksImV4cCI6MTc3NjI4MTM3OX0.Xp3oCiu-39om7UGb3fCPHl4qRKLSsKM5rT2doqo5MjE") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"accountId\" : \"z5YpPGHQO\", " + 
                    " \"seatType\" : 660, " + 
                    " \"date\" : \"1946-11-26\", " + 
                    " \"assurance\" : 636, " + 
                    " \"foodPrice\" : 1.4114508624768226E9, " + 
                    " \"stationName\" : \"7AJyZ\", " + 
                    " \"storeName\" : \"N79xtaQXxPYF01\", " + 
                    " \"consigneeWeight\" : -2.392599861665128E8, " + 
                    " \"isWithin\" : true " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/preserveservice/preserve")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/preserveservice/preserve"))
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("ff1f0109-625"));
    }
    
    
    /**
    * Calls:
    * (403) POST:/api/v1/preserveservice/preserve
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_1_postOnPreserveReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/preserveservice/preserve'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NzYyNzc3NzksImV4cCI6MTc3NjI4MTM3OX0.Xp3oCiu-39om7UGb3fCPHl4qRKLSsKM5rT2doqo5MjE") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"contactsId\" : \"9\", " + 
                    " \"from\" : \"cvHnoi\", " + 
                    " \"assurance\" : 775, " + 
                    " \"foodType\" : 202, " + 
                    " \"foodName\" : \"hWn3c33gfuuwXU\", " + 
                    " \"stationName\" : \"dCW8tsun_C\", " + 
                    " \"handleDate\" : \"AFudv\", " + 
                    " \"consigneePhone\" : \"D1oJr8XGK\" " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/preserveservice/preserve")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }


}
