/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-15T18:43:25.230845620Z[GMT]
 * <br>
*  The generated test suite contains 6 tests
 * <br>
*  Covered targets: 22
 * <br>
*  Used time: 0h 1m 21s
 * <br>
*  Needed budget for current results: 100%
 * <br>
*  This file contains test cases that are likely to indicate faults.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_ts_admin_basic_service_none_faults {

    
    private static String baseUrlOfSut = "http://localhost:8888";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (500) GET:/api/v1/adminbasicservice/adminbasic/prices
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_0_getOnPricesShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("application/json")
                .get(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminbasicservice/adminbasic/prices"))
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("6a413b9a-1317"));
    }
    
    
    /**
    * Calls:
    * 1 - (500) POST:/api/v1/adminbasicservice/adminbasic/prices
    * 2 - (500) POST:/api/v1/adminbasicservice/adminbasic/prices
    * 3 - (500) POST:/api/v1/adminbasicservice/adminbasic/prices
    * 4 - (403) GET:/api/v1/adminbasicservice/adminbasic/prices
    * Found 7 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_1_getOnPricesShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("application/json")
                .contentType("application/json")
                .body(" { " + 
                    " \"trainType\" : \"7nLGuIPqK\", " + 
                    " \"firstClassPriceRate\" : -1.6677261783722466E8 " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminbasicservice/adminbasic/prices"))
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("6a413b9a-1324"));
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("application/json")
                .contentType("application/json")
                .body(" { " + 
                    " \"id\" : \"2nhnXwdisE\", " + 
                    " \"routeId\" : \"p304woxU5cb7w\", " + 
                    " \"basicPriceRate\" : -1.1884284637712148E8, " + 
                    " \"firstClassPriceRate\" : -8.65486775751343E8 " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminbasicservice/adminbasic/prices"))
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("6a413b9a-1325"));
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("application/json")
                .contentType("application/json")
                .body(" { " + 
                    " \"firstClassPriceRate\" : 1.2189537351303534E8 " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminbasicservice/adminbasic/prices"))
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("6a413b9a-1326"));
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (500) POST:/api/v1/adminbasicservice/adminbasic/prices
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_2_postOnPricesShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("application/json")
                .contentType("application/json")
                .body(" { " + 
                    " \"basicPriceRate\" : 1.3535210183465533E9 " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminbasicservice/adminbasic/prices"))
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("6a413b9a-1316"));
    }
    
    
    /**
    * Calls:
    * (403) POST:/api/v1/adminbasicservice/adminbasic/prices
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_3_postOnPricesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"trainType\" : \"7nLGuIPqK\", " + 
                    " \"firstClassPriceRate\" : -1.6677261783722466E8 " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (500) DELETE:/api/v1/adminbasicservice/adminbasic/stations/{id}
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_4_deleteOnStationShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/adminbasicservice/adminbasic/stations/{id}'.
        given().accept("application/json")
                .delete(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/stations/H0gnu8PUo")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminbasicservice/adminbasic/stations/H0gnu8PUo"))
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("6a413b9a-1315"));
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/api/v1/adminbasicservice/adminbasic/stations/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_5_deleteOnStationReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/adminbasicservice/adminbasic/stations/{id}'.
        given().accept("*/*")
                .delete(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/stations/Jp9J1ink")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }


}
