/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-15T04:21:28.505614226Z[GMT]
 * <br>
*  The generated test suite contains 1 tests
 * <br>
*  Covered targets: 5
 * <br>
*  Used time: 0h 1m 36s
 * <br>
*  Needed budget for current results: 50%
 * <br>
*  This file contains test cases that are likely to indicate faults.
*/
public class EvoMaster_ts_order_service_admin_faults {

    
    private static String baseUrlOfSut = "http://localhost:8888";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (503) PUT:/api/v1/orderservice/order
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_0_putOnOrderReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 503 not defined for path '/orderservice/order'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiI3YWRkZDMyZC1lODgyLTQ4ZjUtODFkMi0wOGIwODE4NmNmMWIiLCJpYXQiOjE3Nzc4NzkxMjcsImV4cCI6MTc3Nzg4MjcyN30.VwywVTRiKZSLt9_dKLaFjQzhHBm1-HeJV3Y7BHKuorA") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"boughtDate\": \"1985-01-00\", " + 
                    " \"travelDate\": \"1968-08-23\", " + 
                    " \"travelTime\": \"1999-12-20T18:24:34.835-16:36\", " + 
                    " \"documentType\": 357, " + 
                    " \"from\": \"48e3pySY_\", " + 
                    " \"status\": 253 " + 
                    " } ")
                .put(baseUrlOfSut + "/api/v1/orderservice/order")
                .then()
                .statusCode(503)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/orderservice/order"))
                .body("'status'", numberMatches(503.0))
                .body("'error'", containsString("Service Unavailable"))
                .body("'requestId'", containsString("d8c09a3c-118"));
    }


}
