/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2025-12-18T04:11:35.257989863Z[GMT]
 * <br>
*  The generated test suite contains 2 tests
 * <br>
*  Covered targets: 9
 * <br>
*  Used time: 0h 1m 4s
 * <br>
*  Needed budget for current results: 29%
 * <br>
*  This file contains test cases that are likely to indicate faults.
*/
public class EvoMaster_Test_faults {

    
    private static String baseUrlOfSut = "http://localhost:8888";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (500) PUT:/api/v1/orderservice/order
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_0_putOnOrderShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/orderservice/order'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmZHNlX21pY3Jvc2VydmljZSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpZCI6IjRkMmE0NmM3LTcxY2ItNGNmMS1iNWJiLWI2ODQwNmQ5ZGE2ZiIsImlhdCI6MTc2NjAzMTAyNywiZXhwIjoxNzY2MDM0NjI3fQ.tAorGrsD88IRZ-qEe3R9PB58zSg8x58-nSzymc2JO64") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"id\": \"Cp18LYatcwFKCCDM\", " + 
                    " \"travelTime\": \"2095-08-27T10:08:51Z\", " + 
                    " \"accountId\": \"33Eft_ukOCwGW\", " + 
                    " \"contactsName\": \"b9byhXS6t\", " + 
                    " \"contactsDocumentNumber\": \"3CWXknM\", " + 
                    " \"trainNumber\": \"VO427sUid6\", " + 
                    " \"to\": \"G0BQNZRqh\", " + 
                    " \"status\": 709 " + 
                    " } ")
                .put(baseUrlOfSut + "/api/v1/orderservice/order")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/orderservice/order"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("e06d67eb-1545"));
    }
    
    
    /**
    * Calls:
    * (403) PUT:/api/v1/orderservice/order
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_1_putOnOrderReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/orderservice/order'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmZHNlX21pY3Jvc2VydmljZSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpZCI6IjRkMmE0NmM3LTcxY2ItNGNmMS1iNWJiLWI2ODQwNmQ5ZGE2ZiIsImlhdCI6MTc2NjAzMTAyNywiZXhwIjoxNzY2MDM0NjI3fQ.tAorGrsD88IRZ-qEe3R9PB58zSg8x58-nSzymc2JO64") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"travelDate\": \"2031-13-08\", " + 
                    " \"travelTime\": \"1996-10-24T22:14:56.021Z\", " + 
                    " \"accountId\": \"o1qXgF3arIPl\", " + 
                    " \"contactsName\": \"dwpMQ6\", " + 
                    " \"contactsDocumentNumber\": \"tTNbNQEB9TYjY\", " + 
                    " \"coachNumber\": 614, " + 
                    " \"seatClass\": 803, " + 
                    " \"seatNumber\": \"ssvEr_m3LK\", " + 
                    " \"from\": \"iDeTktGVCg\", " + 
                    " \"to\": \"KzVkjPd3Fk4_I\" " + 
                    " } ")
                .put(baseUrlOfSut + "/api/v1/orderservice/order")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }


}
