/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-15T17:52:54.895577563Z[GMT]
 * <br>
*  The generated test suite contains 3 tests
 * <br>
*  Covered targets: 14
 * <br>
*  Used time: 0h 1m 11s
 * <br>
*  Needed budget for current results: 33%
 * <br>
*  This file contains test cases that are likely to indicate faults.
*/
public class EvoMaster_ts-admin-order-service_user_faults {

    
    private static String baseUrlOfSut = "http://localhost:8888";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (500) PUT:/api/v1/adminorderservice/adminorder
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_0_putOnAdminorderShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/adminorderservice/adminorder'.
        given().accept("application/json")
                .contentType("application/json")
                .body(" { " + 
                    " \"id\": \"yH7fmjt\", " + 
                    " \"boughtDate\": \"2077-00-11\", " + 
                    " \"travelDate\": \"2048-13-00\", " + 
                    " \"accountId\": \"kjX\", " + 
                    " \"contactsDocumentNumber\": \"I1nXkbi\", " + 
                    " \"trainNumber\": \"E4aapmxUoiF2nUo\", " + 
                    " \"coachNumber\": 670, " + 
                    " \"from\": \"GO\", " + 
                    " \"price\": 0.9774147751172579 " + 
                    " } ")
                .put(baseUrlOfSut + "/api/v1/adminorderservice/adminorder")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminorderservice/adminorder"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("f6292085-825"));
    }
    
    
    /**
    * Calls:
    * (500) DELETE:/api/v1/adminorderservice/adminorder/{orderId}/{trainNumber}
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_1_deleteOnAdminordShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/adminorderservice/adminorder/{orderId}/{trainNumber}'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmZHNlX21pY3Jvc2VydmljZSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpZCI6IjRkMmE0NmM3LTcxY2ItNGNmMS1iNWJiLWI2ODQwNmQ5ZGE2ZiIsImlhdCI6MTc3NjI3NTUwMSwiZXhwIjoxNzc2Mjc5MTAxfQ.BCpSF83OZ6USEnb6YVS1q5hEZsikTRmOoBhZe4mC4k4") // Fixed Headers
                .delete(baseUrlOfSut + "/api/v1/adminorderservice/adminorder/en_w9ydCIWd/AxYnbA75C")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminorderservice/adminorder/en_w9ydCIWd/AxYnbA75C"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("f6292085-828"));
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/api/v1/adminorderservice/adminorder/{orderId}/{trainNumber}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_2_deleteOnAdminordReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/adminorderservice/adminorder/{orderId}/{trainNumber}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmZHNlX21pY3Jvc2VydmljZSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpZCI6IjRkMmE0NmM3LTcxY2ItNGNmMS1iNWJiLWI2ODQwNmQ5ZGE2ZiIsImlhdCI6MTc3NjI3NTUwMSwiZXhwIjoxNzc2Mjc5MTAxfQ.BCpSF83OZ6USEnb6YVS1q5hEZsikTRmOoBhZe4mC4k4") // Fixed Headers
                .delete(baseUrlOfSut + "/api/v1/adminorderservice/adminorder/8WrICqc9/vSC2Cq")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }


}
