/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2025-12-18T04:24:36.269774162Z[GMT]
 * <br>
*  The generated test suite contains 2 tests
 * <br>
*  Covered targets: 6
 * <br>
*  Used time: 0h 1m 3s
 * <br>
*  Needed budget for current results: 80%
 * <br>
*  This file contains test cases that are likely to indicate faults.
*/
public class EvoMaster_Test_faults {

    
    private static String baseUrlOfSut = "http://localhost:8888";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (503) PATCH:/api/v1/assuranceservice/assurances/{assuranceId}/{orderId}/{typeIndex}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_0_patchOnAssurReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 503 not defined for path '/assuranceservice/assurances/{assuranceId}/{orderId}/{typeIndex}'.
        given().accept("application/json")
                .patch(baseUrlOfSut + "/api/v1/assuranceservice/assurances/cCiIZU1tSzw4sC/PWw67d/90")
                .then()
                .statusCode(503)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/assuranceservice/assurances/cCiIZU1tSzw4sC/PWw67d/90"))
                .body("'status'", numberMatches(503.0))
                .body("'error'", containsString("Service Unavailable"))
                .body("'requestId'", containsString("b9bdbe78-2350"));
    }
    
    
    /**
    * Calls:
    * (503) PATCH:/api/v1/assuranceservice/assurances/{assuranceId}/{orderId}/{typeIndex}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_1_patchOnAssurReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 503 not defined for path '/assuranceservice/assurances/{assuranceId}/{orderId}/{typeIndex}'.
        given().accept("application/json")
                .patch(baseUrlOfSut + "/api/v1/assuranceservice/assurances/7bSeeVhWG4Ib/ihbavMxzZ/-1996903597")
                .then()
                .statusCode(503)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/assuranceservice/assurances/7bSeeVhWG4Ib/ihbavMxzZ/-1996903597"))
                .body("'status'", numberMatches(503.0))
                .body("'error'", containsString("Service Unavailable"))
                .body("'requestId'", containsString("b9bdbe78-2351"));
    }


}
