/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-15T17:40:02.336568073Z[GMT]
 * <br>
*  The generated test suite contains 9 tests
 * <br>
*  Covered targets: 34
 * <br>
*  Used time: 0h 1m 56s
 * <br>
*  Needed budget for current results: 66%
 * <br>
*  This file contains test cases that are likely to indicate faults.
*/
public class EvoMaster_ts-admin-basic-service_admin_faults {

    
    private static String baseUrlOfSut = "http://localhost:8888";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * 1 - (500) POST:/api/v1/adminbasicservice/adminbasic/prices
    * 2 - (403) DELETE:/api/v1/adminbasicservice/adminbasic/stations/{id}
    * 3 - (500) POST:/api/v1/adminbasicservice/adminbasic/prices
    * 4 - (500) GET:/api/v1/adminbasicservice/adminbasic/prices
    * 5 - (500) DELETE:/api/v1/adminbasicservice/adminbasic/stations/{id}
    * 6 - (200) POST:/api/v1/adminbasicservice/adminbasic/prices
    * 7 - (500) POST:/api/v1/adminbasicservice/adminbasic/prices
    * 8 - (500) DELETE:/api/v1/adminbasicservice/adminbasic/stations/{id}
    * 9 - (500) GET:/api/v1/adminbasicservice/adminbasic/prices
    * Found 15 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_0_getOnPricesShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NzYyNzQ2ODIsImV4cCI6MTc3NjI3ODI4Mn0.rCu-tuU4pApUaMXI325_0Fd3ROUb-ZOY7dBl0k84Tws") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"id\": \"vhMfQw\", " + 
                    " \"trainType\": \"WsZCZcycQUqya_CT\", " + 
                    " \"routeId\": \"MNajTe8IKba\", " + 
                    " \"basicPriceRate\": 0.5704657965203657, " + 
                    " \"firstClassPriceRate\": 0.38721113436172394 " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminbasicservice/adminbasic/prices"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("e13ff816-115"));
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/adminbasicservice/adminbasic/stations/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NzYyNzQ2ODIsImV4cCI6MTc3NjI3ODI4Mn0.rCu-tuU4pApUaMXI325_0Fd3ROUb-ZOY7dBl0k84Tws") // Fixed Headers
                .delete(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/stations/UYaiR4O62GwCxJ4g")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NzYyNzQ2ODIsImV4cCI6MTc3NjI3ODI4Mn0.rCu-tuU4pApUaMXI325_0Fd3ROUb-ZOY7dBl0k84Tws") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"id\": \"YlwGDqTzFK\", " + 
                    " \"trainType\": \"IvTVbrym2\", " + 
                    " \"routeId\": \"kN2PsN8nkoxzQE\" " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminbasicservice/adminbasic/prices"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("e13ff816-118"));
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NzYyNzQ2ODIsImV4cCI6MTc3NjI3ODI4Mn0.rCu-tuU4pApUaMXI325_0Fd3ROUb-ZOY7dBl0k84Tws") // Fixed Headers
                .get(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminbasicservice/adminbasic/prices"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("e13ff816-120"));
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/adminbasicservice/adminbasic/stations/{id}'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NzYyNzQ2ODIsImV4cCI6MTc3NjI3ODI4Mn0.rCu-tuU4pApUaMXI325_0Fd3ROUb-ZOY7dBl0k84Tws") // Fixed Headers
                .delete(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/stations/maxCLkijILA")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminbasicservice/adminbasic/stations/maxCLkijILA"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("e13ff816-121"));
        
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NzYyNzQ2ODIsImV4cCI6MTc3NjI3ODI4Mn0.rCu-tuU4pApUaMXI325_0Fd3ROUb-ZOY7dBl0k84Tws") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"id\": \"HHwvdtzYbv\", " + 
                    " \"basicPriceRate\": 0.7473234708283137, " + 
                    " \"firstClassPriceRate\": 0.5304025343053032 " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(1.0))
                .body("'msg'", containsString("Create success"))
                .body("'data'.'trainType'", nullValue())
                .body("'data'.'routeId'", nullValue())
                .body("'data'.'basicPriceRate'", numberMatches(0.7473234708283137))
                .body("'data'.'firstClassPriceRate'", numberMatches(0.5304025343053032));
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NzYyNzQ2ODIsImV4cCI6MTc3NjI3ODI4Mn0.rCu-tuU4pApUaMXI325_0Fd3ROUb-ZOY7dBl0k84Tws") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"trainType\": \"MU\", " + 
                    " \"routeId\": \"djdd\", " + 
                    " \"firstClassPriceRate\": 0.5599988983363684 " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminbasicservice/adminbasic/prices"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("e13ff816-124"));
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/adminbasicservice/adminbasic/stations/{id}'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NzYyNzQ2ODIsImV4cCI6MTc3NjI3ODI4Mn0.rCu-tuU4pApUaMXI325_0Fd3ROUb-ZOY7dBl0k84Tws") // Fixed Headers
                .delete(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/stations/aUSRpPf5yQwVt7q")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminbasicservice/adminbasic/stations/aUSRpPf5yQwVt7q"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("e13ff816-125"));
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NzYyNzQ2ODIsImV4cCI6MTc3NjI3ODI4Mn0.rCu-tuU4pApUaMXI325_0Fd3ROUb-ZOY7dBl0k84Tws") // Fixed Headers
                .get(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminbasicservice/adminbasic/prices"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("e13ff816-126"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/api/v1/adminbasicservice/adminbasic/prices
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_1_getOnPricesShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NzYyNzQ2ODIsImV4cCI6MTc3NjI3ODI4Mn0.rCu-tuU4pApUaMXI325_0Fd3ROUb-ZOY7dBl0k84Tws") // Fixed Headers
                .get(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminbasicservice/adminbasic/prices"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("e13ff816-99"));
    }
    
    
    /**
    * Calls:
    * (500) POST:/api/v1/adminbasicservice/adminbasic/prices
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_2_postOnPricesShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NzYyNzQ2ODIsImV4cCI6MTc3NjI3ODI4Mn0.rCu-tuU4pApUaMXI325_0Fd3ROUb-ZOY7dBl0k84Tws") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"trainType\": \"1y9kj\", " + 
                    " \"routeId\": \"ERM\", " + 
                    " \"firstClassPriceRate\": 0.5762238218320535 " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminbasicservice/adminbasic/prices"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("e13ff816-97"));
    }
    
    
    /**
    * Calls:
    * (403) GET:/api/v1/adminbasicservice/adminbasic/prices
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_3_getOnPricesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NzYyNzQ2ODIsImV4cCI6MTc3NjI3ODI4Mn0.rCu-tuU4pApUaMXI325_0Fd3ROUb-ZOY7dBl0k84Tws") // Fixed Headers
                .get(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) POST:/api/v1/adminbasicservice/adminbasic/prices
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_4_postOnPricesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"id\": \"u43\", " + 
                    " \"trainType\": \"8Sfx6Q_H\", " + 
                    " \"basicPriceRate\": 0.518277457409972 " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) POST:/api/v1/adminbasicservice/adminbasic/prices
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_5_postOnPricesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NzYyNzQ2ODIsImV4cCI6MTc3NjI3ODI4Mn0.rCu-tuU4pApUaMXI325_0Fd3ROUb-ZOY7dBl0k84Tws") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"firstClassPriceRate\": 0.03327550008171176 " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (500) DELETE:/api/v1/adminbasicservice/adminbasic/stations/{id}
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_6_deleteOnStationShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/adminbasicservice/adminbasic/stations/{id}'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NzYyNzQ2ODIsImV4cCI6MTc3NjI3ODI4Mn0.rCu-tuU4pApUaMXI325_0Fd3ROUb-ZOY7dBl0k84Tws") // Fixed Headers
                .delete(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/stations/R")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminbasicservice/adminbasic/stations/R"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("e13ff816-94"));
    }
    
    
    /**
    * Calls:
    * (200) DELETE:/api/v1/adminbasicservice/adminbasic/stations/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_7_deleteOnStationReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/data'] Instance type (null) does not match any allowed primitive type (allowed: ["object"])
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NzYyNzQ2ODIsImV4cCI6MTc3NjI3ODI4Mn0.rCu-tuU4pApUaMXI325_0Fd3ROUb-ZOY7dBl0k84Tws") // Fixed Headers
                .delete(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/stations/j")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(0.0))
                .body("'msg'", containsString("Station not exist"))
                .body("'data'", nullValue());
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/api/v1/adminbasicservice/adminbasic/stations/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_8_deleteOnStationReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/adminbasicservice/adminbasic/stations/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NzYyNzQ2ODIsImV4cCI6MTc3NjI3ODI4Mn0.rCu-tuU4pApUaMXI325_0Fd3ROUb-ZOY7dBl0k84Tws") // Fixed Headers
                .delete(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/stations/aUSRpPf5yQwVt7q")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }


}
