/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-15T17:41:42.617352128Z[GMT]
 * <br>
*  The generated test suite contains 5 tests
 * <br>
*  Covered targets: 18
 * <br>
*  Used time: 0h 1m 37s
 * <br>
*  Needed budget for current results: 64%
 * <br>
*  This file contains test cases that are likely to indicate faults.
*/
public class EvoMaster_ts-admin-order-service_admin_faults {

    
    private static String baseUrlOfSut = "http://localhost:8888";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (500) PUT:/api/v1/adminorderservice/adminorder
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_0_putOnAdminorderShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/adminorderservice/adminorder'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NzYyNzQ4MDMsImV4cCI6MTc3NjI3ODQwM30.KSAhIqk0PYeuMdRyalzD3RVTbkXIwe04UdbslxDR_IE") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"boughtDate\": \"1964-09-08\", " + 
                    " \"travelDate\": \"1990-04-02\", " + 
                    " \"travelTime\": \"1954-02-13T02:24:49+16:06\", " + 
                    " \"accountId\": \"Xjk\", " + 
                    " \"contactsDocumentNumber\": \"0\", " + 
                    " \"coachNumber\": 153, " + 
                    " \"seatNumber\": \"h_sbsVbKDRIxgo_\", " + 
                    " \"from\": \"AC7cwMvqpRdodT\", " + 
                    " \"to\": \"bir5aRE1\", " + 
                    " \"price\": 0.7589485648152173 " + 
                    " } ")
                .put(baseUrlOfSut + "/api/v1/adminorderservice/adminorder")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminorderservice/adminorder"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("6451eb67-207"));
    }
    
    
    /**
    * Calls:
    * (403) PUT:/api/v1/adminorderservice/adminorder
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_1_putOnAdminorderReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/adminorderservice/adminorder'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NzYyNzQ4MDMsImV4cCI6MTc3NjI3ODQwM30.KSAhIqk0PYeuMdRyalzD3RVTbkXIwe04UdbslxDR_IE") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"id\": \"6D0ZrwlqCu\", " + 
                    " \"travelTime\": \"2034-02-17T04:20:22.124Z\", " + 
                    " \"accountId\": \"yIFy\", " + 
                    " \"contactsName\": \"Ck\", " + 
                    " \"from\": \"\", " + 
                    " \"to\": \"heQIOsML0yqyWP7\", " + 
                    " \"status\": 632 " + 
                    " } ")
                .put(baseUrlOfSut + "/api/v1/adminorderservice/adminorder")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (500) DELETE:/api/v1/adminorderservice/adminorder/{orderId}/{trainNumber}
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_2_deleteOnAdminordShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/adminorderservice/adminorder/{orderId}/{trainNumber}'.
        given().accept("application/json")
                .delete(baseUrlOfSut + "/api/v1/adminorderservice/adminorder/GoucPQ/Ko21W_kNzocxw")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminorderservice/adminorder/GoucPQ/Ko21W_kNzocxw"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("6451eb67-208"));
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/api/v1/adminorderservice/adminorder/{orderId}/{trainNumber}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_3_deleteOnAdminordReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/adminorderservice/adminorder/{orderId}/{trainNumber}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NzYyNzQ4MDMsImV4cCI6MTc3NjI3ODQwM30.KSAhIqk0PYeuMdRyalzD3RVTbkXIwe04UdbslxDR_IE") // Fixed Headers
                .delete(baseUrlOfSut + "/api/v1/adminorderservice/adminorder/Gn6MNb3YW5DI06NM/mPC4FOOZYfObB")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/api/v1/adminorderservice/adminorder/{orderId}/{trainNumber}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_4_deleteOnAdminordReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/adminorderservice/adminorder/{orderId}/{trainNumber}'.
        given().accept("*/*")
                .delete(baseUrlOfSut + "/api/v1/adminorderservice/adminorder/DhVuRcykV_/mfj0fY")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }


}
