/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-15T18:33:16.960989696Z[GMT]
 * <br>
*  The generated test suite contains 4 tests
 * <br>
*  Covered targets: 17
 * <br>
*  Used time: 0h 1m 5s
 * <br>
*  Needed budget for current results: 30%
 * <br>
*  This file contains test cases that are likely to indicate faults.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_ts_admin_order_service_user_faults {

    
    private static String baseUrlOfSut = "http://localhost:8888";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (500) PUT:/api/v1/adminorderservice/adminorder
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_0_putOnAdminorderShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/adminorderservice/adminorder'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmZHNlX21pY3Jvc2VydmljZSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpZCI6IjRkMmE0NmM3LTcxY2ItNGNmMS1iNWJiLWI2ODQwNmQ5ZGE2ZiIsImlhdCI6MTc3ODQ0NDI4NSwiZXhwIjoxNzc4NDQ3ODg1fQ.mNH7GZ4mKP6oRWC5YxdRfPA9MfPe-sJ3XCo5Y3xYFLA") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"id\" : \"Mj0szmmpSPE\", " + 
                    " \"contactsName\" : \"EidQBLdFfk_3moWP\", " + 
                    " \"documentType\" : 968, " + 
                    " \"contactsDocumentNumber\" : \"9QbNahcKh8KyiBV\", " + 
                    " \"trainNumber\" : \"Tg2\", " + 
                    " \"coachNumber\" : 212, " + 
                    " \"from\" : \"YlQvQnY9QoGr2\", " + 
                    " \"status\" : 614, " + 
                    " \"price\" : -1.9194780095342138E8 " + 
                    " } ")
                .put(baseUrlOfSut + "/api/v1/adminorderservice/adminorder")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminorderservice/adminorder"))
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("ac898519-785"));
    }
    
    
    /**
    * Calls:
    * (403) PUT:/api/v1/adminorderservice/adminorder
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_1_putOnAdminorderReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/adminorderservice/adminorder'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmZHNlX21pY3Jvc2VydmljZSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpZCI6IjRkMmE0NmM3LTcxY2ItNGNmMS1iNWJiLWI2ODQwNmQ5ZGE2ZiIsImlhdCI6MTc3ODQ0NDI4NSwiZXhwIjoxNzc4NDQ3ODg1fQ.mNH7GZ4mKP6oRWC5YxdRfPA9MfPe-sJ3XCo5Y3xYFLA") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"id\" : \"z45GeTkVf3x\", " + 
                    " \"boughtDate\" : \"2053-02-05\", " + 
                    " \"travelDate\" : \"2040-01-32\", " + 
                    " \"travelTime\" : \"2040-05-02T24:27:58Z\", " + 
                    " \"contactsName\" : \"tO9Rb3y0b\", " + 
                    " \"trainNumber\" : \"sKD3OTue\", " + 
                    " \"seatNumber\" : \"yjQgzGR3a1\", " + 
                    " \"from\" : \"8Gld\", " + 
                    " \"status\" : 897 " + 
                    " } ")
                .put(baseUrlOfSut + "/api/v1/adminorderservice/adminorder")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (500) DELETE:/api/v1/adminorderservice/adminorder/{orderId}/{trainNumber}
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_2_deleteOnAdminordShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/adminorderservice/adminorder/{orderId}/{trainNumber}'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmZHNlX21pY3Jvc2VydmljZSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpZCI6IjRkMmE0NmM3LTcxY2ItNGNmMS1iNWJiLWI2ODQwNmQ5ZGE2ZiIsImlhdCI6MTc3ODQ0NDI4NSwiZXhwIjoxNzc4NDQ3ODg1fQ.mNH7GZ4mKP6oRWC5YxdRfPA9MfPe-sJ3XCo5Y3xYFLA") // Fixed Headers
                .delete(baseUrlOfSut + "/api/v1/adminorderservice/adminorder/IJ7HcNj0INT/NFTa")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminorderservice/adminorder/IJ7HcNj0INT/NFTa"))
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("ac898519-783"));
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/api/v1/adminorderservice/adminorder/{orderId}/{trainNumber}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_3_deleteOnAdminordReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/adminorderservice/adminorder/{orderId}/{trainNumber}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmZHNlX21pY3Jvc2VydmljZSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpZCI6IjRkMmE0NmM3LTcxY2ItNGNmMS1iNWJiLWI2ODQwNmQ5ZGE2ZiIsImlhdCI6MTc3ODQ0NDI4NSwiZXhwIjoxNzc4NDQ3ODg1fQ.mNH7GZ4mKP6oRWC5YxdRfPA9MfPe-sJ3XCo5Y3xYFLA") // Fixed Headers
                .delete(baseUrlOfSut + "/api/v1/adminorderservice/adminorder/mBDsPnmanpfM/kGyCH5_Ca2")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }


}
