/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2025-12-18T04:01:35.997180068Z[GMT]
 * <br>
*  The generated test suite contains 3 tests
 * <br>
*  Covered targets: 14
 * <br>
*  Used time: 0h 1m 4s
 * <br>
*  Needed budget for current results: 13%
 * <br>
*  This file contains test cases that are likely to indicate faults.
*/
public class EvoMaster_Test_faults {

    
    private static String baseUrlOfSut = "http://localhost:8888";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (500) PUT:/api/v1/adminuserservice/users
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_0_putOnUsersShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/adminuserservice/users'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NjYwMzA0MjksImV4cCI6MTc2NjAzNDAyOX0.pzI2x3nTQY9voYqIhHiPoC9qZKd6co-DApE7yXaS0ks") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"userName\": \"WARKZGz2oBSYO0\", " + 
                    " \"gender\": 660, " + 
                    " \"documentNum\": \"ikccklswz7EmwHi\" " + 
                    " } ")
                .put(baseUrlOfSut + "/api/v1/adminuserservice/users")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminuserservice/users"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("8845ae03-863"));
    }
    
    
    /**
    * Calls:
    * (200) PUT:/api/v1/adminuserservice/users
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_1_putOnUsersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/data'] Instance type (null) does not match any allowed primitive type (allowed: ["object"])
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NjYwMzA0MjksImV4cCI6MTc2NjAzNDAyOX0.pzI2x3nTQY9voYqIhHiPoC9qZKd6co-DApE7yXaS0ks") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"userName\": \"\", " + 
                    " \"gender\": 457, " + 
                    " \"email\": \"oXXdVl\" " + 
                    " } ")
                .put(baseUrlOfSut + "/api/v1/adminuserservice/users")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(0.0))
                .body("'msg'", containsString("Update user error"))
                .body("'data'", nullValue());
    }
    
    
    /**
    * Calls:
    * (403) PUT:/api/v1/adminuserservice/users
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_2_putOnUsersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/adminuserservice/users'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NjYwMzA0MjksImV4cCI6MTc2NjAzNDAyOX0.pzI2x3nTQY9voYqIhHiPoC9qZKd6co-DApE7yXaS0ks") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"userId\": \"piYz4xP\", " + 
                    " \"password\": \"6Km\", " + 
                    " \"email\": \"rQYb71aWWipUt\" " + 
                    " } ")
                .put(baseUrlOfSut + "/api/v1/adminuserservice/users")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }


}
