/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2025-12-18T03:52:58.349234101Z[GMT]
 * <br>
*  The generated test suite contains 5 tests
 * <br>
*  Covered targets: 21
 * <br>
*  Used time: 0h 1m 7s
 * <br>
*  Needed budget for current results: 12%
 * <br>
*  This file contains test cases that are likely to indicate faults.
*/
public class EvoMaster_Test_faults {

    
    private static String baseUrlOfSut = "http://localhost:8888";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (500) GET:/api/v1/contactservice/contacts
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_0_getOnContactsShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/contactservice/contacts'.
        given().accept("application/json")
                .get(baseUrlOfSut + "/api/v1/contactservice/contacts")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/contactservice/contacts"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("209bbcc7-190"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/v1/contactservice/contacts
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_1_getOnContactsReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/data'] Instance type (array) does not match any allowed primitive type (allowed: ["object"])
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NjYwMjk5MDksImV4cCI6MTc2NjAzMzUwOX0.M8peeRvmHmjNwUK9-fn_F2Wnv8APghP-89_LouhKWQ8") // Fixed Headers
                .get(baseUrlOfSut + "/api/v1/contactservice/contacts")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(1.0))
                .body("'msg'", containsString("Success"))
                .body("'data'.size()", equalTo(8))
                .body("'data'[0].'accountId'", containsString("XoQ_MfKUXOQI"))
                .body("'data'[0].'name'", nullValue())
                .body("'data'[0].'documentType'", numberMatches(1.0))
                .body("'data'[0].'documentNumber'", nullValue())
                .body("'data'[0].'phoneNumber'", nullValue())
                .body("'data'[1].'accountId'", containsString("4d2a46c7-71cb-4cf1-b5bb-b68406d9da6f"))
                .body("'data'[1].'name'", containsString("Contacts_Two"))
                .body("'data'[1].'documentType'", numberMatches(1.0))
                .body("'data'[1].'documentNumber'", containsString("DocumentNumber_Two"))
                .body("'data'[1].'phoneNumber'", containsString("ContactsPhoneNum_Two"))
                .body("'data'[2].'accountId'", nullValue())
                .body("'data'[2].'name'", containsString("4P"))
                .body("'data'[2].'documentType'", numberMatches(0.0))
                .body("'data'[2].'documentNumber'", nullValue())
                .body("'data'[2].'phoneNumber'", nullValue())
                ; // Skipping assertions on the remaining 5 elements. This limit of 3 elements can be increased in the configurations
    }
    
    
    /**
    * Calls:
    * (500) DELETE:/api/v1/contactservice/contacts/{contactsId}
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_2_deleteOnContactShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/contactservice/contacts/{contactsId}'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NjYwMjk5MDksImV4cCI6MTc2NjAzMzUwOX0.M8peeRvmHmjNwUK9-fn_F2Wnv8APghP-89_LouhKWQ8") // Fixed Headers
                .delete(baseUrlOfSut + "/api/v1/contactservice/contacts/Q")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/contactservice/contacts/Q"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("209bbcc7-187"));
    }
    
    
    /**
    * Calls:
    * (200) DELETE:/api/v1/contactservice/contacts/{contactsId}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_3_deleteOnContactReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/data'] Instance type (string) does not match any allowed primitive type (allowed: ["object"])
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NjYwMjk5MDksImV4cCI6MTc2NjAzMzUwOX0.M8peeRvmHmjNwUK9-fn_F2Wnv8APghP-89_LouhKWQ8") // Fixed Headers
                .delete(baseUrlOfSut + "/api/v1/contactservice/contacts/Gzz8u")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(1.0))
                .body("'msg'", containsString("Delete success"))
                .body("'data'", containsString("Gzz8u"));
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/api/v1/contactservice/contacts/{contactsId}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_4_deleteOnContactReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/contactservice/contacts/{contactsId}'.
        given().accept("*/*")
                .delete(baseUrlOfSut + "/api/v1/contactservice/contacts/lCD")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }


}
