/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-15T18:29:38.304906448Z[GMT]
 * <br>
*  The generated test suite contains 2 tests
 * <br>
*  Covered targets: 9
 * <br>
*  Used time: 0h 1m 9s
 * <br>
*  Needed budget for current results: 7%
 * <br>
*  This file contains test cases that are likely to indicate faults.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_ts-order-service_admin_faults {

    
    private static String baseUrlOfSut = "http://localhost:8888";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (500) PUT:/api/v1/orderservice/order
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_0_putOnOrderShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/orderservice/order'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NzYyNzc3MDcsImV4cCI6MTc3NjI4MTMwN30.LS3gjJFOD_Y0tPAtPv-xZTC_-0TTIdCkzOGhdETq8VA") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"id\" : \"8OiA\", " + 
                    " \"boughtDate\" : \"2008-04-04\", " + 
                    " \"accountId\" : \"1tHc7bdpk\", " + 
                    " \"contactsName\" : \"kXJz\", " + 
                    " \"documentType\" : 404, " + 
                    " \"contactsDocumentNumber\" : \"0y4Yj\", " + 
                    " \"from\" : \"cGeu9FVDx4EUG\", " + 
                    " \"to\" : \"hn\" " + 
                    " } ")
                .put(baseUrlOfSut + "/api/v1/orderservice/order")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/orderservice/order"))
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("03ffc052-557"));
    }
    
    
    /**
    * Calls:
    * (403) PUT:/api/v1/orderservice/order
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_1_putOnOrderReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/orderservice/order'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"id\" : \"ro3spSRw2MD\", " + 
                    " \"boughtDate\" : \"2081-06-25\", " + 
                    " \"travelTime\" : \"1904-05-20T06:44:42Z\", " + 
                    " \"documentType\" : 444, " + 
                    " \"contactsDocumentNumber\" : \"\", " + 
                    " \"trainNumber\" : \"9nmnIBfWlgXhYi\", " + 
                    " \"seatClass\" : 888, " + 
                    " \"seatNumber\" : \"lT8IoFaM9\", " + 
                    " \"from\" : \"tAQRVm6St\", " + 
                    " \"price\" : -4.985107515922662E7 " + 
                    " } ")
                .put(baseUrlOfSut + "/api/v1/orderservice/order")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }


}
