/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-15T18:11:30.967589685Z[GMT]
 * <br>
*  The generated test suite contains 2 tests
 * <br>
*  Covered targets: 8
 * <br>
*  Used time: 0h 1m 6s
 * <br>
*  Needed budget for current results: 22%
 * <br>
*  This file contains test cases that are likely to indicate faults.
*/
public class EvoMaster_ts-preserve-service_none_faults {

    
    private static String baseUrlOfSut = "http://localhost:8888";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (500) POST:/api/v1/preserveservice/preserve
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_0_postOnPreserveShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/preserveservice/preserve'.
        given().accept("application/json")
                .contentType("application/json")
                .body(" { " + 
                    " \"accountId\": \"n4Mc1xAI\", " + 
                    " \"contactsId\": \"R\", " + 
                    " \"seatType\": 331, " + 
                    " \"date\": \"1928-01-24\", " + 
                    " \"to\": \"\", " + 
                    " \"assurance\": 757, " + 
                    " \"foodType\": 815, " + 
                    " \"foodPrice\": 0.597086544054554, " + 
                    " \"handleDate\": \"kDJ\", " + 
                    " \"consigneeName\": \"dR6IQHu1k\", " + 
                    " \"consigneeWeight\": 0.5663583750003013 " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/preserveservice/preserve")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/preserveservice/preserve"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("ed930566-1845"));
    }
    
    
    /**
    * Calls:
    * (403) POST:/api/v1/preserveservice/preserve
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_1_postOnPreserveReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/preserveservice/preserve'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"accountId\": \"tD\", " + 
                    " \"date\": \"2034-08-00\", " + 
                    " \"from\": \"zwTdzsfPFNLyodzz\", " + 
                    " \"to\": \"xLdDhrvV\", " + 
                    " \"assurance\": 50, " + 
                    " \"foodType\": 852, " + 
                    " \"foodName\": \"Yj1AP_E\", " + 
                    " \"foodPrice\": 0.49912593235138947, " + 
                    " \"stationName\": \"Rs_\", " + 
                    " \"handleDate\": \"9fhAroKS\", " + 
                    " \"consigneeName\": \"a9HaObi3mXcp\", " + 
                    " \"consigneePhone\": \"lD6jd\" " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/preserveservice/preserve")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }


}
