/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-15T04:38:40.510753952Z[GMT]
 * <br>
*  The generated test suite contains 1 tests
 * <br>
*  Covered targets: 5
 * <br>
*  Used time: 0h 1m 37s
 * <br>
*  Needed budget for current results: 50%
 * <br>
*  This file contains test cases that are likely to indicate faults.
*/
public class EvoMaster_ts_order_service_user_faults {

    
    private static String baseUrlOfSut = "http://localhost:8888";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (503) PUT:/api/v1/orderservice/order
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_0_putOnOrderReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 503 not defined for path '/orderservice/order'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmZHNlX21pY3Jvc2VydmljZSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpZCI6IjRkMmE0NmM3LTcxY2ItNGNmMS1iNWJiLWI2ODQwNmQ5ZGE2ZiIsImlhdCI6MTc3Nzg3OTEyOCwiZXhwIjoxNzc3ODgyNzI4fQ.omAkJ6ibHxUTR2bqoxe3CdGN4TIMp8cKOg6X58pyb_8") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"id\": \"eVyYAKn\", " + 
                    " \"boughtDate\": \"2014-12-24\", " + 
                    " \"travelTime\": \"1999-03-13T06:35:27-00:18\", " + 
                    " \"accountId\": \"8eiy4HTr2\", " + 
                    " \"trainNumber\": \"talVSW8\", " + 
                    " \"coachNumber\": 420, " + 
                    " \"seatClass\": 445, " + 
                    " \"from\": \"U0PSoYY\", " + 
                    " \"price\": 0.6873959907150939 " + 
                    " } ")
                .put(baseUrlOfSut + "/api/v1/orderservice/order")
                .then()
                .statusCode(503)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/orderservice/order"))
                .body("'status'", numberMatches(503.0))
                .body("'error'", containsString("Service Unavailable"))
                .body("'requestId'", containsString("30a2c752-158"));
    }


}
