/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2025-12-18T03:54:42.657713812Z[GMT]
 * <br>
*  The generated test suite contains 6 tests
 * <br>
*  Covered targets: 27
 * <br>
*  Used time: 0h 1m 40s
 * <br>
*  Needed budget for current results: 100%
 * <br>
*  This file contains test cases that are likely to indicate faults.
*/
public class EvoMaster_Test_faults {

    
    private static String baseUrlOfSut = "http://localhost:8888";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (500) GET:/api/v1/adminbasicservice/adminbasic/prices
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_0_getOnPricesShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NjYwMjk5ODAsImV4cCI6MTc2NjAzMzU4MH0.wYo9isGw3fRavSi-W906xTQYYm25YueCV5QFEEoiwb0") // Fixed Headers
                .get(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminbasicservice/adminbasic/prices"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("b62f9d4f-298"));
    }
    
    
    /**
    * Calls:
    * 1 - (403) POST:/api/v1/adminbasicservice/adminbasic/prices
    * 2 - (500) POST:/api/v1/adminbasicservice/adminbasic/prices
    * 3 - (500) POST:/api/v1/adminbasicservice/adminbasic/prices
    * 4 - (200) GET:/api/v1/adminbasicservice/adminbasic/prices
    * Found 6 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_1_getOnPricesShowsFaults_100_101() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NjYwMjk5ODAsImV4cCI6MTc2NjAzMzU4MH0.wYo9isGw3fRavSi-W906xTQYYm25YueCV5QFEEoiwb0") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"id\": \"SFGvVcQ4MMHHa\", " + 
                    " \"basicPriceRate\": 0.48849308205745423 " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NjYwMjk5ODAsImV4cCI6MTc2NjAzMzU4MH0.wYo9isGw3fRavSi-W906xTQYYm25YueCV5QFEEoiwb0") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"id\": \"AiWp1uNpa0gZHx\", " + 
                    " \"routeId\": \"2Cir\", " + 
                    " \"basicPriceRate\": 0.9171885418634638, " + 
                    " \"firstClassPriceRate\": 0.09262696372460955 " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminbasicservice/adminbasic/prices"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("b62f9d4f-301"));
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NjYwMjk5ODAsImV4cCI6MTc2NjAzMzU4MH0.wYo9isGw3fRavSi-W906xTQYYm25YueCV5QFEEoiwb0") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"id\": \"knZGfFzH8yAINz\" " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminbasicservice/adminbasic/prices"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("b62f9d4f-303"));
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/data'] Instance type (array) does not match any allowed primitive type (allowed: ["object"])
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NjYwMjk5ODAsImV4cCI6MTc2NjAzMzU4MH0.wYo9isGw3fRavSi-W906xTQYYm25YueCV5QFEEoiwb0") // Fixed Headers
                .get(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(1.0))
                .body("'msg'", containsString("Success"))
                .body("'data'.size()", equalTo(974))
                .body("'data'[0].'trainType'", nullValue())
                .body("'data'[0].'routeId'", nullValue())
                .body("'data'[0].'basicPriceRate'", numberMatches(0.0))
                .body("'data'[0].'firstClassPriceRate'", numberMatches(0.0))
                .body("'data'[1].'trainType'", nullValue())
                .body("'data'[1].'routeId'", containsString("YXS4EvuRkYHnfxu"))
                .body("'data'[1].'basicPriceRate'", numberMatches(0.0))
                .body("'data'[1].'firstClassPriceRate'", numberMatches(0.0))
                .body("'data'[2].'trainType'", nullValue())
                .body("'data'[2].'routeId'", nullValue())
                .body("'data'[2].'basicPriceRate'", numberMatches(0.0))
                .body("'data'[2].'firstClassPriceRate'", numberMatches(0.0))
                ; // Skipping assertions on the remaining 971 elements. This limit of 3 elements can be increased in the configurations
    }
    
    
    /**
    * Calls:
    * (500) POST:/api/v1/adminbasicservice/adminbasic/prices
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_2_postOnPricesShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NjYwMjk5ODAsImV4cCI6MTc2NjAzMzU4MH0.wYo9isGw3fRavSi-W906xTQYYm25YueCV5QFEEoiwb0") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"id\": \"3OTjM_q8IvXFZ8\", " + 
                    " \"routeId\": \"i\" " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminbasicservice/adminbasic/prices"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("b62f9d4f-285"));
    }
    
    
    /**
    * Calls:
    * (403) POST:/api/v1/adminbasicservice/adminbasic/prices
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_3_postOnPricesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/adminbasicservice/adminbasic/prices'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NjYwMjk5ODAsImV4cCI6MTc2NjAzMzU4MH0.wYo9isGw3fRavSi-W906xTQYYm25YueCV5QFEEoiwb0") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"routeId\": \"sKhds0dZ5\", " + 
                    " \"basicPriceRate\": 0.9898820078686315, " + 
                    " \"firstClassPriceRate\": 0.8522259903113127 " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/prices")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (500) DELETE:/api/v1/adminbasicservice/adminbasic/stations/{id}
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_4_deleteOnStationShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/adminbasicservice/adminbasic/stations/{id}'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NjYwMjk5ODAsImV4cCI6MTc2NjAzMzU4MH0.wYo9isGw3fRavSi-W906xTQYYm25YueCV5QFEEoiwb0") // Fixed Headers
                .delete(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/stations/Uxh7xWS_VxcYzoa9")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminbasicservice/adminbasic/stations/Uxh7xWS_VxcYzoa9"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("b62f9d4f-284"));
    }
    
    
    /**
    * Calls:
    * (200) DELETE:/api/v1/adminbasicservice/adminbasic/stations/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_5_deleteOnStationReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/data'] Instance type (null) does not match any allowed primitive type (allowed: ["object"])
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NjYwMjk5ODAsImV4cCI6MTc2NjAzMzU4MH0.wYo9isGw3fRavSi-W906xTQYYm25YueCV5QFEEoiwb0") // Fixed Headers
                .delete(baseUrlOfSut + "/api/v1/adminbasicservice/adminbasic/stations/huGyj2vFHgc4qVcw")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(0.0))
                .body("'msg'", containsString("Station not exist"))
                .body("'data'", nullValue());
    }


}
