/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-15T04:19:48.592123802Z[GMT]
 * <br>
*  The generated test suite contains 1 tests
 * <br>
*  Covered targets: 5
 * <br>
*  Used time: 0h 1m 36s
 * <br>
*  Needed budget for current results: 50%
 * <br>
*  This file contains test cases that are likely to indicate faults.
*/
public class EvoMaster_ts-inside-payment-service_admin_faults {

    
    private static String baseUrlOfSut = "http://localhost:8888";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (503) POST:/api/v1/inside_pay_service/inside_payment/account
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_0_postOnAccountReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 503 not defined for path '/inside_pay_service/inside_payment/account'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NzYyMjY2ODksImV4cCI6MTc3NjIzMDI4OX0.Ncijga4j_H3bl-P7jHEcL_eio-_wigXgJUU3-oqwOOE") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"userId\": \"\" " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/inside_pay_service/inside_payment/account")
                .then()
                .statusCode(503)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/inside_pay_service/inside_payment/account"))
                .body("'status'", numberMatches(503.0))
                .body("'error'", containsString("Service Unavailable"))
                .body("'requestId'", containsString("de68dded-114"));
    }


}
