/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-15T04:09:55.559027114Z[GMT]
 * <br>
*  The generated test suite contains 2 tests
 * <br>
*  Covered targets: 9
 * <br>
*  Used time: 0h 2m 6s
 * <br>
*  Needed budget for current results: 100%
 * <br>
*  This file contains test cases that are likely to indicate faults.
*/
public class EvoMaster_ts_admin_order_service_admin_faults {

    
    private static String baseUrlOfSut = "http://localhost:8888";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (503) PUT:/api/v1/adminorderservice/adminorder
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_0_putOnAdminorderReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 503 not defined for path '/adminorderservice/adminorder'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiI3YWRkZDMyZC1lODgyLTQ4ZjUtODFkMi0wOGIwODE4NmNmMWIiLCJpYXQiOjE3Nzc4NzkxMjcsImV4cCI6MTc3Nzg4MjcyN30.VwywVTRiKZSLt9_dKLaFjQzhHBm1-HeJV3Y7BHKuorA") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"id\": \"QxTY\", " + 
                    " \"boughtDate\": \"2094-02-32\", " + 
                    " \"travelTime\": \"1949-10-04T13:25:37.944-13:21\", " + 
                    " \"accountId\": \"lnuC\", " + 
                    " \"contactsDocumentNumber\": \"bzvOI\", " + 
                    " \"coachNumber\": 141, " + 
                    " \"seatClass\": 940, " + 
                    " \"seatNumber\": \"y7C\", " + 
                    " \"status\": 947, " + 
                    " \"price\": 0.5976203453573206 " + 
                    " } ")
                .put(baseUrlOfSut + "/api/v1/adminorderservice/adminorder")
                .then()
                .statusCode(503)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminorderservice/adminorder"))
                .body("'status'", numberMatches(503.0))
                .body("'error'", containsString("Service Unavailable"))
                .body("'requestId'", containsString("9e4986a3-90"));
    }
    
    
    /**
    * Calls:
    * (503) DELETE:/api/v1/adminorderservice/adminorder/{orderId}/{trainNumber}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_1_deleteOnAdminordReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 503 not defined for path '/adminorderservice/adminorder/{orderId}/{trainNumber}'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiI3YWRkZDMyZC1lODgyLTQ4ZjUtODFkMi0wOGIwODE4NmNmMWIiLCJpYXQiOjE3Nzc4NzkxMjcsImV4cCI6MTc3Nzg4MjcyN30.VwywVTRiKZSLt9_dKLaFjQzhHBm1-HeJV3Y7BHKuorA") // Fixed Headers
                .delete(baseUrlOfSut + "/api/v1/adminorderservice/adminorder/uuhRkvP8jV/f")
                .then()
                .statusCode(503)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminorderservice/adminorder/uuhRkvP8jV/f"))
                .body("'status'", numberMatches(503.0))
                .body("'error'", containsString("Service Unavailable"))
                .body("'requestId'", containsString("9e4986a3-91"));
    }


}
