/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-15T18:39:49.934978831Z[GMT]
 * <br>
*  The generated test suite contains 3 tests
 * <br>
*  Covered targets: 14
 * <br>
*  Used time: 0h 1m 13s
 * <br>
*  Needed budget for current results: 21%
 * <br>
*  This file contains test cases that are likely to indicate faults.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_ts-inside-payment-service_user_faults {

    
    private static String baseUrlOfSut = "http://localhost:8888";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (500) POST:/api/v1/inside_pay_service/inside_payment/account
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_0_postOnAccountShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/inside_pay_service/inside_payment/account'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmZHNlX21pY3Jvc2VydmljZSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpZCI6IjRkMmE0NmM3LTcxY2ItNGNmMS1iNWJiLWI2ODQwNmQ5ZGE2ZiIsImlhdCI6MTc3NjI3ODMxNCwiZXhwIjoxNzc2MjgxOTE0fQ.K0hS0dOQI_iPQDck1zQ0FKRB1antoklesjUzBW99M4Y") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"userId\" : \"YfYXL02phgE2\", " + 
                    " \"money\" : \"rvxlPTUMP5t\" " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/inside_pay_service/inside_payment/account")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/inside_pay_service/inside_payment/account"))
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("61ab3d4e-1091"));
    }
    
    
    /**
    * Calls:
    * (200) POST:/api/v1/inside_pay_service/inside_payment/account
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_1_postOnAccountReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type [Path '/data'] Instance type (null) does not match any allowed primitive type (allowed: ["object"])
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmZHNlX21pY3Jvc2VydmljZSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpZCI6IjRkMmE0NmM3LTcxY2ItNGNmMS1iNWJiLWI2ODQwNmQ5ZGE2ZiIsImlhdCI6MTc3NjI3ODMxNCwiZXhwIjoxNzc2MjgxOTE0fQ.K0hS0dOQI_iPQDck1zQ0FKRB1antoklesjUzBW99M4Y") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"userId\" : \"o2fFMWrtRFuSA\", " + 
                    " \"money\" : \"\" " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/inside_pay_service/inside_payment/account")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(1))
                .body("'msg'", containsString("Create Account Success"))
                .body("'data'", nullValue());
    }
    
    
    /**
    * Calls:
    * (403) POST:/api/v1/inside_pay_service/inside_payment/account
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_2_postOnAccountReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/inside_pay_service/inside_payment/account'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmZHNlX21pY3Jvc2VydmljZSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpZCI6IjRkMmE0NmM3LTcxY2ItNGNmMS1iNWJiLWI2ODQwNmQ5ZGE2ZiIsImlhdCI6MTc3NjI3ODMxNCwiZXhwIjoxNzc2MjgxOTE0fQ.K0hS0dOQI_iPQDck1zQ0FKRB1antoklesjUzBW99M4Y") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"userId\" : \"6qLPz\" " + 
                    " } ")
                .post(baseUrlOfSut + "/api/v1/inside_pay_service/inside_payment/account")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }


}
