/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-15T17:42:59.490496033Z[GMT]
 * <br>
*  The generated test suite contains 3 tests
 * <br>
*  Covered targets: 10
 * <br>
*  Used time: 0h 1m 14s
 * <br>
*  Needed budget for current results: 28%
 * <br>
*  This file contains test cases that are likely to indicate faults.
*/
public class EvoMaster_ts-admin-user-service_admin_faults {

    
    private static String baseUrlOfSut = "http://localhost:8888";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (500) PUT:/api/v1/adminuserservice/users
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_0_putOnUsersShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/adminuserservice/users'.
        given().accept("application/json")
                .contentType("application/json")
                .body(" { " + 
                    " \"userId\": \"nzXoNfL\", " + 
                    " \"gender\": 112, " + 
                    " \"documentType\": -1672121409, " + 
                    " \"documentNum\": \"KV1UCUB0Fh\", " + 
                    " \"email\": \"Y1\" " + 
                    " } ")
                .put(baseUrlOfSut + "/api/v1/adminuserservice/users")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminuserservice/users"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("904b255f-288"));
    }
    
    
    /**
    * Calls:
    * 1 - (500) PUT:/api/v1/adminuserservice/users
    * 2 - (403) PUT:/api/v1/adminuserservice/users
    * Found 3 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_1_putOnUsersShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/adminuserservice/users'.
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NzYyNzQ5MDMsImV4cCI6MTc3NjI3ODUwM30.U_dInPOAbMBvNapY3dr0Px38SJEmJtv5fWe-ftHY23A") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"userId\": \"csX\", " + 
                    " \"userName\": \"KrCXjwqWrCCe5Z\" " + 
                    " } ")
                .put(baseUrlOfSut + "/api/v1/adminuserservice/users")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'path'", containsString("/api/v1/adminuserservice/users"))
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'requestId'", containsString("904b255f-292"));
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/adminuserservice/users'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"password\": \"QngPNZNqUWSua1o4\", " + 
                    " \"documentType\": 158, " + 
                    " \"documentNum\": \"\" " + 
                    " } ")
                .put(baseUrlOfSut + "/api/v1/adminuserservice/users")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) PUT:/api/v1/adminuserservice/users
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_2_putOnUsersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/adminuserservice/users'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWQiOiIyZmIyYjZhZS1lMWQ2LTQ2NTUtYTYwZC1lMjcxNzU2ZmQ0YWEiLCJpYXQiOjE3NzYyNzQ5MDMsImV4cCI6MTc3NjI3ODUwM30.U_dInPOAbMBvNapY3dr0Px38SJEmJtv5fWe-ftHY23A") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"userId\": \"Qj\", " + 
                    " \"password\": \"R_K38tHwa\", " + 
                    " \"gender\": 331, " + 
                    " \"documentType\": 283, " + 
                    " \"documentNum\": \"aVP8GoJ2S\", " + 
                    " \"email\": \"J8COXH6qS\" " + 
                    " } ")
                .put(baseUrlOfSut + "/api/v1/adminuserservice/users")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }


}
